package com.fivesense.api.auth.app;

import com.fivesense.api.auth.domain.*;
import com.fivesense.api.auth.dto.AuthDtos;
import com.fivesense.api.auth.infra.PasswordResetTokenRepository;
import com.fivesense.api.shared.error.ApiException;
import com.fivesense.api.shared.infra.EmailService;
import com.fivesense.api.users.domain.*;
import com.fivesense.api.users.infra.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.password.PasswordEncoder;
import java.lang.reflect.Field;
import java.time.Instant;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class AuthServiceTests {
    private UserRepository users;private PasswordResetTokenRepository resetTokens;private PasswordEncoder passwords;private SessionService sessions;private JwtTokenService jwt;private EmailService email;private AuthService service;
    @BeforeEach void setup(){users=mock(UserRepository.class);resetTokens=mock(PasswordResetTokenRepository.class);passwords=mock(PasswordEncoder.class);sessions=mock(SessionService.class);jwt=mock(JwtTokenService.class);email=mock(EmailService.class);service=new AuthService(users,resetTokens,passwords,sessions,jwt,email);when(passwords.encode(anyString())).thenReturn("encoded");}

    @Test void loginIssuesChallengeOnlyForValidFirstAccessCredentials(){AppUser user=user(UserRole.ADMIN,UserStatus.FIRST_ACCESS);var issue=issue(user,SessionType.PASSWORD_CHANGE);when(users.findByEmailIgnoreCase("test@example.com")).thenReturn(Optional.of(user));when(passwords.matches("Temp#123",user.getPasswordHash())).thenReturn(true);when(sessions.create(eq(user),any(),eq(true))).thenReturn(issue);when(jwt.issue(eq(user),eq(issue.session()),isNull(),eq(true),any())).thenReturn(token(true));assertThat(service.login(new AuthDtos.LoginRequest(" Test@Example.com ","Temp#123")).passwordChangeRequired()).isTrue();}
    @Test void loginRejectsInvalidCredentialsAndInactiveAccounts(){AppUser user=user(UserRole.ADMIN,UserStatus.ACTIVE);when(users.findByEmailIgnoreCase(anyString())).thenReturn(Optional.of(user));when(passwords.matches(anyString(),anyString())).thenReturn(false);assertThatThrownBy(()->service.login(new AuthDtos.LoginRequest("test@example.com","bad"))).isInstanceOf(ApiException.class);user.update("Test",user.getEmail(),user.getRole(),UserStatus.INACTIVE,Instant.now());when(passwords.matches(anyString(),anyString())).thenReturn(true);assertThatThrownBy(()->service.login(new AuthDtos.LoginRequest("test@example.com","valid"))).isInstanceOf(ApiException.class);}
    @Test void refreshRotatesViewerSessionAndRejectsDisabledUser(){AppUser viewer=user(UserRole.VIEWER,UserStatus.ACTIVE);var issue=issue(viewer,SessionType.REFRESHABLE);when(sessions.rotate(eq("refresh"),any())).thenReturn(issue);when(users.findById(viewer.getId())).thenReturn(Optional.of(viewer));when(jwt.issue(eq(viewer),eq(issue.session()),eq("next"),eq(false),any())).thenReturn(token(false));assertThat(service.refresh("refresh").passwordChangeRequired()).isFalse();viewer.update("Test",viewer.getEmail(),viewer.getRole(),UserStatus.INACTIVE,Instant.now());assertThatThrownBy(()->service.refresh("refresh")).isInstanceOf(ApiException.class);verify(sessions).revoke(eq(issue.session().getId()),eq(viewer.getId()),any());}
    @Test void changePasswordChecksCurrentValueAndRevokesExistingSessions(){AppUser user=user(UserRole.MANAGER,UserStatus.ACTIVE);var issue=issue(user,SessionType.ACCESS_ONLY);when(users.findById(user.getId())).thenReturn(Optional.of(user));when(passwords.matches("OldStrong#1",user.getPasswordHash())).thenReturn(true);when(sessions.create(eq(user),any(),eq(false))).thenReturn(issue);when(jwt.issue(eq(user),eq(issue.session()),isNull(),eq(false),any())).thenReturn(token(false));var result=service.changePassword(user.getId(),issue.session().getId(),new AuthDtos.ChangePasswordRequest("OldStrong#1","NewStrong#2","NewStrong#2"));assertThat(result.passwordChangeRequired()).isFalse();verify(sessions).revokeAll(eq(user.getId()),any());}
    @Test void changePasswordRejectsInvalidCurrentPasswordAndWeakPassword(){AppUser user=user(UserRole.MANAGER,UserStatus.ACTIVE);when(users.findById(user.getId())).thenReturn(Optional.of(user));when(passwords.matches(anyString(),anyString())).thenReturn(false);assertThatThrownBy(()->service.changePassword(user.getId(),UUID.randomUUID(),new AuthDtos.ChangePasswordRequest("wrong","NewStrong#2","NewStrong#2"))).isInstanceOf(ApiException.class);assertThatThrownBy(()->service.changePassword(user.getId(),UUID.randomUUID(),new AuthDtos.ChangePasswordRequest("x","weak","weak"))).isInstanceOf(ApiException.class);}
    @Test void logoutRevokesCurrentSession(){UUID uid=UUID.randomUUID(),sid=UUID.randomUUID();service.logout(uid,sid);verify(sessions).revoke(eq(sid),eq(uid),any());}
    @Test void resetRequestAlwaysReturnsNeutralMessageAndSendsOnlyForActiveAccount(){AppUser active=user(UserRole.VIEWER,UserStatus.ACTIVE);when(users.findByEmailIgnoreCase("test@example.com")).thenReturn(Optional.of(active));when(users.findByEmailIgnoreCase("missing@example.com")).thenReturn(Optional.empty());assertThat(service.requestPasswordReset("TEST@example.com").message()).contains("eligible");assertThat(service.requestPasswordReset("missing@example.com").message()).contains("eligible");verify(resetTokens).save(any(PasswordResetToken.class));verify(email).send(eq(active.getEmail()),contains("Recuperação"),contains("token"));}
    @Test void confirmResetConsumesTokenChangesPasswordAndRevokesSessions(){AppUser user=user(UserRole.VIEWER,UserStatus.ACTIVE);String raw="reset-token";PasswordResetToken token=new PasswordResetToken(user.getId(),SessionService.hash(raw),Instant.now().plusSeconds(600),Instant.now());when(resetTokens.findByTokenHash(SessionService.hash(raw))).thenReturn(Optional.of(token));when(users.findById(user.getId())).thenReturn(Optional.of(user));service.confirmPasswordReset(new AuthDtos.ResetConfirmRequest(raw,"NewStrong#2","NewStrong#2"));assertThat(token.getUsedAt()).isNotNull();verify(sessions).revokeAll(eq(user.getId()),any());}
    @Test void confirmResetRejectsUsedExpiredOrUnknownToken(){String raw="reset-token";PasswordResetToken expired=new PasswordResetToken(UUID.randomUUID(),SessionService.hash(raw),Instant.now().minusSeconds(1),Instant.now());when(resetTokens.findByTokenHash(SessionService.hash(raw))).thenReturn(Optional.of(expired));assertThatThrownBy(()->service.confirmPasswordReset(new AuthDtos.ResetConfirmRequest(raw,"NewStrong#2","NewStrong#2"))).isInstanceOf(ApiException.class);when(resetTokens.findByTokenHash(anyString())).thenReturn(Optional.empty());assertThatThrownBy(()->service.confirmPasswordReset(new AuthDtos.ResetConfirmRequest("other","NewStrong#2","NewStrong#2"))).isInstanceOf(ApiException.class);}

    private static AppUser user(UserRole role,UserStatus status){AppUser u=new AppUser("Test","test@example.com","hash",role,status,Instant.now());try{Field f=AppUser.class.getDeclaredField("id");f.setAccessible(true);f.set(u,UUID.randomUUID());}catch(ReflectiveOperationException ex){throw new IllegalStateException(ex);}return u;}
    private static SessionService.SessionIssue issue(AppUser user,SessionType type){Instant now=Instant.now();return new SessionService.SessionIssue(new AuthSession(UUID.randomUUID(),user.getId(),null,type,now,now.plusSeconds(3600)),type==SessionType.REFRESHABLE?"next":null);}
    private static AuthDtos.TokenResponse token(boolean change){return new AuthDtos.TokenResponse("access",null,"Bearer",300,change);}
}
